services:
  laravel:
    image: composer:latest
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
     - ./laravel:/app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
    depends_on:
      - mysql
    command: sleep infinity

  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: POSdatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456789
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: